version: '3.8'
services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: videos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
